require("core.options")
require("core.colorscheme")
require("core.keymaps")

require("plugins-setup")

require("plugins.harpoon")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.mason")
require("plugins.lspsaga")
require("plugins.lspconfig")
require("plugins.which-key")
require("plugins.null-ls")
require("plugins.toggleterm")
require("plugins.leap")
require("plugins.autopairs")
require("plugins.hlslens")
require("plugins.indent-blankline")
require("plugins.comment")
require("plugins.nvim-scrollbar")
